// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJneAy1QIuD1Csbpk9RpKGSlyA3P62zkg',
    appId: '1:500823112162:web:6f1323c9d1e01f04f9e1bb',
    messagingSenderId: '500823112162',
    projectId: 'fluttergram619',
    authDomain: 'fluttergram619.firebaseapp.com',
    storageBucket: 'fluttergram619.appspot.com',
    measurementId: 'G-T9J8G9D0XJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ8g01z6A58jS0mNtz-C840sKPZx2Dw9w',
    appId: '1:500823112162:android:c88723ccaacc2d3af9e1bb',
    messagingSenderId: '500823112162',
    projectId: 'fluttergram619',
    storageBucket: 'fluttergram619.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOLQrNrcgChktxDHqPS_ygkIhP9I_JyVU',
    appId: '1:500823112162:ios:ca16871276667ab9f9e1bb',
    messagingSenderId: '500823112162',
    projectId: 'fluttergram619',
    storageBucket: 'fluttergram619.appspot.com',
    iosBundleId: 'com.example.fluttergram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOLQrNrcgChktxDHqPS_ygkIhP9I_JyVU',
    appId: '1:500823112162:ios:1c7d332c4cea0d7ff9e1bb',
    messagingSenderId: '500823112162',
    projectId: 'fluttergram619',
    storageBucket: 'fluttergram619.appspot.com',
    iosBundleId: 'com.example.fluttergram.RunnerTests',
  );
}
